### ISSUE TITLE
v3.5 #Vendor options little reorganisation (picture)

### ISSUE THREAD

**Issue by GeneralSheppard** [noonereally/NW-Profession-Bot#26]
Hello.

This is just an example about how it could be interesting to save lines and space for this Vendor options.

I'm sorry if this is unwelcome.
Here' the ideas:

Best regards

**Comment by noonereally** [comment]
I've removed the image, it showed two of your chars at the bottom.

**Comment by GeneralSheppard** [comment]
Oh Thank You! Sorry for this.
