### ISSUE TITLE
v3.5 #Prof levels few ideas

### ISSUE THREAD

**Issue by GeneralSheppard** [noonereally/NW-Profession-Bot#29]
Hello.

I would like to request few ideas about this Prof levels tab.
##### Sort professions A to Z

Alchemy, Artificing, Jewelcrafting, Leadership, Leatherworking, Mailsmithing, Platesmithing, Tailoring, Weaponsmithing [BlackIceShaping] etc...

Event:
Black Ice Shaping through the Icewind Dale Campaign
Midsummer Provisioning during the Midsummer Festival
Siege Defense Effort aka "Siege Event" during the Siege of Neverwinter
Simril Lightcrafting aka "Winter Event" during Winter Festivale

Best regards,

**Comment by noonereally** [comment]
Actually they are on purpose not in alphabetical order, most professions are not interesting for most chars, so the more important are first (first 3). It shouldn't be a problem to reorder the rest but BI Shaping is not event profession and yet I don't think it  should be at the beginning.

**Comment by GeneralSheppard** [comment]
Yes I understand your point of view. I separated Main and Event to distinguish them.
Do you think that you can direct me into the code where I can modify to sort them A to Z ?
If users do not use them I would be interested to put into my local script.

**Comment by noonereally** [comment]
Line 1519:

```
var defaultCharStatistics = {
        general: {
            nextTask: null,
            lastSCAVisit: null,
            refineCounter: 0,
            refineCounterReset: Date.now(),
            diamonds: 0,
            gold: 0,
            rad: 0,
            rBI: 0,
            BI: 0,
            refined: 0,
            refineLimitLeft: 0,
            emptyBagSlots: 0,
            activeSlots: 0,
        },
        professions: {
            // Names must match unsafeWindow.client.dataModel.model.ent.main.itemassignmentcategories.categories.displayname
            "Leadership": { level: 0, workersUsed: [], workersUnused: [] },
            "Alchemy": { level: 0, workersUsed: [], workersUnused: [] },
            "Jewelcrafting": { level: 0, workersUsed: [], workersUnused: [] },
            "Weaponsmithing": { level: 0,workersUsed: [], workersUnused: [] },
            "Artificing": { level: 0, workersUsed: [], workersUnused: [] },
            "Mailsmithing": { level: 0, workersUsed: [], workersUnused: []},
            "Platesmithing": { level: 0, workersUsed: [], workersUnused: [] },
            "Leatherworking": { level: 0, workersUsed: [], workersUnused: [] },
            "Tailoring": { level: 0, workersUsed: [], workersUnused: [] },
            "Black Ice Shaping": { level: 0, workersUsed: [], workersUnused: [] },
            /*
            "Winter Event":     { level: 0, workersUsed: [], workersUnused: [] },
            "Siege Event":      { level: 0, workersUsed: [], workersUnused: [] },
            */
        },
```

You will probably have to reset all settings (the button) after the change or you will not see the difference.

**Comment by GeneralSheppard** [comment]
Thank you.
About the Black Ice Shaping I assume there are a way to make it shorter like BlackIce or something because actually the full name overflows lines.

**Comment by noonereally** [comment]
If i remember correctly the names must match model names, they can be cutoff when displayed, 
or in single line (committed a change now so the line wont break).

**Comment by GeneralSheppard** [comment]
Okay I see.
What about few more options.

As you have found that users will not make 'more than 4' I guess professions (need 3prof Lv20 to unlock a slot) would it be possible :
- to hide other professions ? choose which professions you want to display and focus
- to bold highest level we reached from all our characters (ex: char1 got 12 in alchemy it's bold and others not)

I wonder if there are a way to track how long tasks have been achieved it can be a good statistic
char1 Alchemy Lv9  13Hrs  230 tasks etc etc

Edit: Black Ice Shaping fixed
https://github.com/noonereally/NW-Profession-Bot/issues/29#issuecomment-102650069

**Comment by Phr33d0m** [comment]
My OCD ticks really hard whenever I see unsorted (alphabetically in this case) list of items... I like the idea of some more general type of sorting rather than "importance" (which is mostly relative to the user).
