### ISSUE TITLE
V3.5 #Ressource Tracker few ideas

### ISSUE THREAD

**Issue by GeneralSheppard** [noonereally/NW-Profession-Bot#30]
Hello.

Here are some ideas about Ressource Tracker tab.
This specific tab is really interesting when we exchange items between our characters let's say that on my secondary character I crafted ressources because my main character is busy with 6Hrs tasks; it can be interesting to have a global points of you of all crafted items.
1. Each professions who got materials have their own tab.
   You have to click on the profession you want to display all ressources/materials available.
   example:

Alchemy 'click on me' display materials/ressources
----------------char 1-----char 2------char 3---total
Prof Level------8------------4----------0----------
Simple Pelt----7-------------7---------0---------14
Pine Wood ----7-------------7---------0---------14

others...

I want to make [Rank 4 Experimentation] x4 who need :
- BVitriol: 28
- GVitriol: 28
- AquaVitae: 4

My 2 characters got 3 slots and produce 6Vitriol/Hr x3slots x2char I'm able to produce 36 Vitriol/Hr 
but only 18Vitriol/Hr/Char and I want to exchange 10 Vitriol from my 2nd character because I choose this character to only deal with materials.

Okay this is just a simulation and I hope it's not funny to read lol
Hard to explain in english sorry for that.

Best regards

**Comment by noonereally** [comment]
1. Need to keep all the inventory of all the characters saved.
2. There is no good way to put more than 8 chars in one row.
3. Will have to run a sort+merge on every UI update.

Not practical, sorry.
