### ISSUE TITLE
v3.5 Attempt auto login not working after a hard-manual update.

### ISSUE THREAD

**Issue by GeneralSheppard** [noonereally/NW-Profession-Bot#31]
Hello.

I was running previous v3.5 version when I paused it to delete this version from Tampermonkey and then install the newest. I opened Gateway with the new updated version and 'of course' I was not able to attempt autologin.

Do there are a way that our first action/first time we run it we have a pop up to be able to write our login infos ?

Right now (with newest update) the script still run and attempt to login without success until that we pause it.

Best regards.

**Comment by noonereally** [comment]
I believe it's fixed now. 
I've added a forced settings reset for people who upgrade from older versions and it got into a loop.

**Comment by GeneralSheppard** [comment]
How Tampermonkey exactly deal with newest version; because just right after you published latest version you got, I tried to hard updates and it failed.

**Comment by noonereally** [comment]
you tried right now ? I updated about 3 min ago.
(the fix for this)

**Comment by GeneralSheppard** [comment]
Fixed! Awesome.
Do you have a time to look into this:
https://github.com/Phr33d0m/NW-Profession-Bot/issues/101

When I sign out manually (script is running), I would like that it stays sign out until I press play to run the script again.

Right now when I sign out manually, the script reconnect automatically in few second when "Attempt to login automatically" is checked. Sign out > pause > stay sign out > play > auto-connect

**Comment by noonereally** [comment]
I'll close this, the other issue is not simple.
