### ISSUE TITLE
v3.5 Leadership taskname have 9slots / AD on each fresh install/update as default

### ISSUE THREAD

**Issue by GeneralSheppard** [noonereally/NW-Profession-Bot#33]
Hello.

After each fresh install/update when we choose our char 'settings we always have Leadership 9 slots and AD profile.

Do there are a specific reason for this ?
Can it be set to 0 slot, default profile  as default setting ?

Edit: 
Understood
Thanks.

Best regards,

**Comment by noonereally** [comment]
Yes, it's a good default, also it's on low priority by default, so if you set any other tasks, they will be chosen first, and if there will be empty slots left they will go towards the leadership.

If you want to set default for yourself, in the profiles section each Task Name has default priority and default slot number.
