### ISSUE TITLE
v3.5 Show all our char' next task Top left

### ISSUE THREAD

**Issue by GeneralSheppard** [noonereally/NW-Profession-Bot#34]
Hello.

It would be interesting to have all our char' next task who is located at Top left.
Also there are a problem with char using more than 6(?) letters where time is on the following line.

Exemple:

Professions Robot
Next task for 1234567
5m 14s
(Next task for 9876541
1m 18s)
Diamonds: xxx,xxx
Gold: xx

As you can see my char name got 7 letters and the time is already the fololowing line.
- Is it possible to extend the width ?

max char name is 20 letters  (just checked right now)

Best regards,

**Comment by noonereally** [comment]
1. Assume you have 50 chars..  you can't have this at the screen, that's why there is a tab.
2. I don't see it, tested with 15 and it shows correctly.

**Comment by GeneralSheppard** [comment]
Only the top 3 char next task maybe ?
Your time is under the char name ?

**Comment by noonereally** [comment]
1. The time is always next line, there is a `<br />` there.
2. Probably not difficult to do, but i really don't see the need, it will only add clutter and I just added a tab with all the task times.

**Comment by GeneralSheppard** [comment]
Looks good for me then :)
Do the width is automatically resize if we have more letters ?

**Comment by noonereally** [comment]
yes, the name shouldn't break.
