### ISSUE TITLE
v3.5 Overwrite choice

### ISSUE THREAD

**Issue by electropica** [noonereally/NW-Profession-Bot#42]
I don't understand well the "overwrite account settings for this char".
None was selected but yet it wasn't using account configuration.
It has end selling what was set in char configuration instead of account configuration.

What exact settings should be overwrite when we check option ?

**Comment by noonereally** [comment]
If it is set, it will use char settings, if not the account.
There was a bug with Altars being sold and the UI options was not there, so I think that is the problem you saw - should be fixed now. 

This way you can have general settings, and if you want specific chars to have unique settigns, check the checkbox and set the char settings in the char tabs

**Comment by electropica** [comment]
Ok thank you.
