### ISSUE TITLE
v3.5 Auto-recover saved data from login form

### ISSUE THREAD

**Issue by GeneralSheppard** [noonereally/NW-Profession-Bot#43]
Hello.

Using Chrome I do save my login to be able to just click to connect.
Would it be possible that the script recover these data (username-mail adress  and  password) from Gateway website and auto-fill up into your form script ?

Best regards,

**Comment by noonereally** [comment]
For what purpose ?
If you do not want the script auto connect you can use chrome auto complete, or you can fill it in the script.

**Comment by GeneralSheppard** [comment]
Indeed I made a mistake I didn't know if was possible to recover data from an existing profile.
I close this issue.

Thanks
