### ISSUE TITLE
[Idea] Vendor all lockboxes click-right option.

### ISSUE THREAD

**Issue by GeneralSheppard** [noonereally/NW-Profession-Bot#50]
Hello.

I do not know what's the point of view of many players but in my case I do not need lockboxes.
Would it be possible to get an option to clickright on the lockboxes and have "Vendor all" just like the picture below ?

http://prntscr.com/78x64l

Open All (13)
Sell All (13)

Thank you.

**Comment by noonereally** [comment]
Why just not click sell, there is an option to sell all right after it.
Sorry, but I do not see a benefit of such option, and not an easy way to add one like that.

**Comment by Phr33d0m** [comment]
To be honest I don't like including stuff in the bot unrelated to its autonomy.

In any case if you want to get rid of all the lockboxes just add it to the auto-vendor regex.

**Comment by GeneralSheppard** [comment]
Thank you I'll do it.
